"""add screenshot_url column

Revision ID: 46bfa0b8719e
Revises: d8b5b929fa99
Create Date: 2025-10-31 15:43:54.441085

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46bfa0b8719e"
down_revision: Union[str, Sequence[str], None] = "d8b5b929fa99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookmark", sa.Column("screenshot_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookmark", "screenshot_url")
    # ### end Alembic commands ###
