"""add s3_key

Revision ID: cc5f801ca9fe
Revises: 46bfa0b8719e
Create Date: 2026-08-21 12:33:48.818312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5f801ca9fe'
down_revision: Union[str, Sequence[str], None] = '46bfa0b8719e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('s3_key', sa.String(), nullable=True))
    op.drop_column('bookmark', 'screenshot_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('screenshot_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bookmark', 's3_key')
    # ### end Alembic commands ###
